pub const Candidate = struct {
    action: []const u8,
    job: []const u8,
    current: []const u8,
    current_ref: []const u8 = "",
    version_comment: []const u8 = "",
    sha_mismatch: bool = false,
    next: []const u8,
    next_label: []const u8 = "",
    next_is_major: bool = false,
    file: []const u8,
    line: u32,
};

pub const sample_candidates = [_]Candidate{
    .{
        .action = "actions/checkout",
        .job = "build-packages",
        .current = "v3",
        .current_ref = "f43a0e5",
        .next = "v4",
        .file = ".github/workflows/ci.yml",
        .line = 12,
    },
    .{
        .action = "pnpm/action-setup",
        .job = "build-packages",
        .current = "v2.4.0",
        .current_ref = "c10b806",
        .next = "v4.1.0",
        .next_is_major = true,
        .file = ".github/workflows/ci.yml",
        .line = 18,
    },
    .{
        .action = "docker/login-action",
        .job = "release",
        .current = "sha:8c29f5",
        .next = "v3.3.0",
        .file = ".github/workflows/release.yml",
        .line = 9,
    },
    .{
        .action = "github/codeql-action/upload-sarif",
        .job = "workflow-security",
        .current = "v4.35.1",
        .current_ref = "c10b806",
        .next = "v4.35.3",
        .file = ".github/workflows/ci-security.yml",
        .line = 24,
    },
    .{
        .action = "astral-sh/setup-uv",
        .job = "workflow-security",
        .current = "v7.6.0",
        .current_ref = "37802ad",
        .next = "v8.1.0",
        .next_is_major = true,
        .file = ".github/workflows/ci-security.yml",
        .line = 31,
    },
};
